version: 0.2
env:
  variables:
    PROJECT: "example"
    UPLOAD_S3: "true"
    S3_BUCKET: "example.pureweb.io"
    DEFAULT_REGION_NAME: "us-west-2"
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo "Building Example repo...."
      - chmod +x codebuild.sh
      - ./codebuild.sh
  post_build:
    commands:
      - echo "Building docker container..."
      - docker build -t 630322998121.dkr.ecr.us-west-2.amazonaws.com/pw5-example .
      - docker push 630322998121.dkr.ecr.us-west-2.amazonaws.com/pw5-example:latest
